title: CUB Robotics & Intelligent Systems Lab
description: Wiki page for internal documentation
theme: just-the-docs

url: https://cub-cs-ris-lab.github.io

aux_links:
  Template Repository: https://github.com/CU-IntelligentSystems/cub-cs-ris-lab.github.io

plugins:
  - jekyll-default-layout
